### ISSUE TITLE
저 이름 잘못 들어갔어요

### ISSUE THREAD

**Issue by HGNB0508** [monun/speculation-resource-pack#24]
강화군 했는데 HGNB0508입니다
HGN0508아니에요ㅠㅠㅠㅠㅠ

**Comment by piese1028** [comment]
풀리퀘로 넣으시면 될듯

**Comment by HGNB0508** [comment]
> 풀리퀘로 넣으시면 될듯

폴리퀘로 파일 이름 수정 가능한가요? 아니면 다른 방법이 있나요
