### ISSUE TITLE
대전 어디갔죠?

### ISSUE THREAD

**Issue by piese1028** [monun/speculation-resource-pack#47]
https://github.com/monun/speculation-resource-pack/pull/8
여기 머지 됬는데 대전이 실종됬

**Comment by zlfn** [comment]
기업과 직접 연관되어서 빠진게 아닐까요?

**Comment by zlfn** [comment]
![스크린샷, 2021-09-23 14-00-54](https://user-images.githubusercontent.com/33383685/134456760-e4c7737d-da6e-4d91-8c70-a1f804865d7a.png)

**Comment by piese1028** [comment]
그런가 봅니다
