### ISSUE TITLE
텍스처 파일 어디다 두나요

### ISSUE THREAD

**Issue by TeamOgsigee** [monun/speculation-resource-pack#49]
리드미파일엔 이렇게 있는데

규칙
기업과 직접 관련된 랜드마크 금지
모델의 박스 40개 이하
모델 파일 경로 assets/minecraft/models/item/<랜드마크이름>/<제작자>/__landmark.json
텍스쳐 경로 assets/minecraft/models/item/<랜드마크이름>/<제작자>/

소스코드에는 textures랑 models 폴더로 나누어져 있는데...
뭐 그냥 textures에 텍스쳐 넣으면 되겠죠?

**Comment by piese1028** [comment]
assets/minecraft/models/item/<랜드마크이름>/<제작자>/
여기다 두시면 됩니다

**Comment by TeamOgsigee** [comment]
두분 다 감사합니다!
