### ISSUE TITLE
군, 시 추가

### ISSUE THREAD

**Issue by w0819** [monun/speculation-resource-pack#9]
README.md에 적여있는 군, 시 말고도 시와 군를 추가 할수 있나요?

**Comment by dytroInc** [comment]
방송에서 최종 게임판으로 나온 지역들만 가능해요. 그 README.md에 안 나온 지역들이 있어서 README.md 말고도 다른 지역은 가능한데 방송에서 나왔던 지역들만 가능해요.

**Comment by w0819** [comment]
아 알겠습니다.

**Comment by w0819** [comment]
> 방송에서 최종 게임판으로 나온 지역들만 가능해요. 그 README.md에 안 나온 지역들이 있어서 README.md 말고도 다른 지역은 가능한데 방송에서 나왔던 지역들만 가능해요.

아 알겠습니다.
